# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$lua\
$time\
$battery\
$memory_usage\
$line_break$character\
"""
# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

# Starship modules

# Palette definitions
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:blue"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "fg:blue"
style_root = "fg:blue"
format = '[$user]($style) - '

[directory]
style = "fg:peach"
truncation_length = 5
truncation_symbol = "…/"
use_os_path_sep = false
format = "[$path ]($style)"

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[on $symbol $branch ](fg:peach)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind)](fg:red)]($style) - '

[git_commit]
commit_hash_length = 4
tag_symbol = '  '
tag_disabled = false
only_detached = false
style = "bg:teal"
format = '[[\($hash$tag\) ](fg:peach)]($style)'

[lua]
symbol = ' '
style = "bg:teal"
format = '[via $symbol$version](fg:green) '

[python]
symbol = " "
style = "bg:teal"
format = '[[via ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )](fg:green)]($style) '

[time]
disabled = false
time_format = "%R"
style = "bg:teal"
format = '- [[ $time ](fg:pink)]($style)'

[battery]
disabled = false
format = '[[$symbol$percentage](fg:pink) ](bg"teal)' 

[memory_usage]
disabled = false
threshold = -1
symbol = " "
format = '[[$symbol$ram_pct](fg:pink) ](bg"teal)' 

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[[󰄛 ](green) ❯](peach)"
error_symbol = "[[󰄛 ](red) ❯](peach)"
